---
- name: Install and configure apache
  hosts: webservers
  become: true
  tasks:
    - name: install mysql
      apt:
        name: mysql-server
        state: present
        update_cache: yes
    - name: ensure it is running
      service:
         name: mysql
         state: started
         enabled: yes
    - name: stop running
      service:
          name: mysql
          state: stopped
    - name: install mysql
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: install a python package
      pip:
         name: requests
         state: present
