---
- name: install a package
  hosts: webservers
  become: true
  vars_files:
   - var.yaml  #using externall file
  tasks:
   - name: install package
     apt:
        name: "{{package_name}}"
        state: present
   - name: install list of packages
     apt:
       name: "{{item}}"
       state: present

     loop:
       - postgresql
       - git
       - php
       - curl
       - wget

   - name: Install nmap only if it's not already installed
     apt:
        name: nmap
        state: present
     when: ansible_facts.packages['nmap'] is not defined
